version: "3"

services:
  web:
    build: .
    image: buzz
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - db_mongo
    volumes:
      - .:/usr/src/app/:rw
      - node_modules:/usr/src/app/node_modules
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  node_modules: